import type { Metadata } from "next";
import ProjectCard from "@/components/ProjectCard";
import SectionHeader from "@/components/SectionHeader";
import { Callout, CapabilityLayer, DiagramLegend, GraphNodeLabel, PageHeader, ProjectMetric, StatusIndicator, TechnicalMetadata, TimelineItem } from "@/components/portfolio";
import { Badge, Button, Card, Container, Divider, ExternalLink, Grid, Heading, IconButton, LinkButton, Section, Stack, Text, VisuallyHidden } from "@/components/ui";
import { projects } from "@/data/projects";
import styles from "./design-system.module.css";

export const metadata: Metadata = { title: "Design System Lab", description: "Documentação viva da fundação visual do portfólio.", robots: { index: false, follow: false } };

const tokens = [
  ["background", "var(--color-background-primary)"], ["surface", "var(--color-surface-primary)"],
  ["primary", "var(--color-accent-primary)"], ["operational", "var(--color-accent-operational)"],
  ["research", "var(--color-accent-research)"], ["education", "var(--color-accent-education)"],
] as const;

export default function DesignSystemLabPage() {
  return <div className={styles.lab}>
    <nav className={styles.labNav} aria-label="Seções do design system"><a href="#tokens">Tokens</a><a href="#type">Tipografia</a><a href="#actions">Ações</a><a href="#layout">Layout</a><a href="#portfolio">Portfólio</a><a href="#accessibility">Acessibilidade</a></nav>
    <Container>
      <PageHeader eyebrow="LAB / foundation 02" title="Uma linguagem visual para sistemas que atravessam camadas." description="Documentação viva e isolada: tokens semânticos, primitives acessíveis e composições orientadas a evidência. O tema funcional desta fase é dark; contraste reforçado já possui fundação estrutural." actions={<Stack direction="responsive" gap={3}><LinkButton href="/lab/sol-portfolio-concept">Ver conceito Sol</LinkButton><LinkButton href="/" variant="secondary">Voltar ao portfólio</LinkButton></Stack>} />

      <Section id="tokens" spacing="compact"><Stack gap={6}><SectionHeader eyebrow="01 / tokens" title="Papéis semânticos, não cores soltas" description="A superfície escolhe o papel; o tema resolve o valor." /><Grid columns={3}>{tokens.map(([name, color]) => <div className={styles.token} style={{ "--token-color": color } as React.CSSProperties} key={name}><span>{name}</span></div>)}</Grid></Stack></Section>

      <Section id="type" spacing="compact"><Stack gap={6}><SectionHeader eyebrow="02 / tipografia" title="Escala com leitura confortável" description="Corpo começa em 16 px; microcopy permanece legível e monospace é reservado a sinais técnicos." /><Card><Stack gap={6}><Heading level={2} size="display">Display / full-cycle</Heading><Heading level={3} size="heading2">Heading / relações entre camadas</Heading><Text>Texto de corpo para explicar decisões, limites e resultados sem comprimir a leitura.</Text><Text variant="mono">mono.signal = observabilidade + precisão</Text><Text variant="caption">CAPTION / METADADO TÉCNICO</Text></Stack></Card></Stack></Section>

      <Section id="actions" spacing="compact"><Stack gap={6}><SectionHeader eyebrow="03 / ações e estado" title="Ação clara, estado visível" description="Variações compartilham foco, dimensões e comportamento reduzido." /><Card><Stack gap={6}><div className={styles.interactiveRow}><Button>Primária</Button><Button variant="secondary">Secundária</Button><Button variant="ghost">Ghost</Button><Button loading>Carregando</Button><Button disabled>Indisponível</Button><IconButton ariaLabel="Adicionar item"><span className={styles.iconGlyph} aria-hidden="true">+</span></IconButton></div><Divider /><div className={styles.interactiveRow}><Badge>neutro</Badge><Badge tone="operational">operação</Badge><Badge tone="research">pesquisa</Badge><Badge tone="education">educação</Badge><Badge tone="success">sucesso</Badge><StatusIndicator status="active" /><StatusIndicator status="risk" /></div><ExternalLink href="https://github.com/albertomateus9">Perfil no GitHub</ExternalLink></Stack></Card></Stack></Section>

      <Section id="layout" spacing="compact"><Stack gap={6}><SectionHeader eyebrow="04 / estrutura" title="Container, Stack, Grid e Card" description="Poucas regras de composição criam ritmo consistente de 320 px ao desktop." /><Grid columns={3}><Card className={styles.sample}><Stack gap={3}><Badge tone="operational">sinal</Badge><Heading level={3} size="heading3">Hardware e RF</Heading><Text variant="small">Uma camada física legível pelo sistema.</Text></Stack></Card><Card variant="research" className={styles.sample}><Stack gap={3}><Badge tone="research">inteligência</Badge><Heading level={3} size="heading3">Dados e modelos</Heading><Text variant="small">Contexto, rastreabilidade e revisão humana.</Text></Stack></Card><Card href="/projects" className={styles.sample}><Stack gap={3}><Badge>interativo</Badge><Heading level={3} size="heading3">Catálogo de projetos</Heading><Text variant="small">O Card pode ser navegável sem virar botão.</Text></Stack></Card></Grid></Stack></Section>

      <Section id="portfolio" spacing="compact"><Stack gap={8}><SectionHeader eyebrow="05 / composições" title="APIs para evidência, trajetória e arquitetura" description="Componentes traduzem o sistema visual para a narrativa profissional." /><Grid columns={3}><ProjectMetric label="Sistemas ativos" value="06" detail="infra → IA" status="active" /><ProjectMetric label="Evidências públicas" value="12+" detail="fontes rastreáveis" status="live" /><ProjectMetric label="Modo" value="full-cycle" detail="pesquisa + entrega" status="research" /></Grid><Callout title="Fronteira de confiança" tone="research">O lab demonstra relações sem acessar notas privadas ou inventar métricas de produção.</Callout><Card><TechnicalMetadata items={[{ label: "Tema", value: "Dark funcional" }, { label: "Contraste", value: "Fundação high-contrast" }, { label: "Motion", value: "Respeita reduced-motion" }, { label: "Viewport", value: "320 px → desktop" }]} /></Card><Grid columns={2}><Card><ol className={styles.capabilities}><CapabilityLayer index="01" label="Sinal" detail="eletrônica, RF e sensores" /><CapabilityLayer index="02" label="Rede" detail="telecom e observabilidade" /><CapabilityLayer index="03" label="Inteligência" detail="dados, visão e agentes" isLast /></ol></Card><Card><ol className={styles.timelineList}><TimelineItem marker="01" title="Base física" description="Telecomunicações, redes e eletromagnetismo." /><TimelineItem marker="02" title="Camada digital" description="Software, dados e interfaces operacionais." /><TimelineItem marker="03" title="Multiplicação" description="Pesquisa, ensino e direção técnica." /></ol></Card></Grid><Card><Stack gap={4}><svg className={styles.diagram} viewBox="0 0 600 240" role="img" aria-label="Exemplo de nós de projeto, área e núcleo"><line x1="300" y1="120" x2="130" y2="70" stroke="var(--color-border-strong)" /><line x1="300" y1="120" x2="470" y2="170" stroke="var(--color-border-strong)" /><GraphNodeLabel x={300} y={120} label="Alberto" kind="core" /><GraphNodeLabel x={130} y={70} label="Projeto" kind="project" /><GraphNodeLabel x={470} y={170} label="Pesquisa" kind="area" /></svg><DiagramLegend items={[{ label: "núcleo" }, { label: "projeto", tone: "operational" }, { label: "área", tone: "research" }]} /></Stack></Card><ProjectCard project={projects[0]} /></Stack></Section>

      <Section id="accessibility" spacing="compact"><Stack gap={6}><SectionHeader eyebrow="06 / acessibilidade" title="Foco, semântica e preferência do usuário" description="Estados nunca dependem só de cor; navegação por teclado e leitura assistiva são parte da API." /><div className={styles.contrastPanel} data-contrast="more"><Stack gap={3}><Heading level={3} size="heading3">Amostra de contraste reforçado</Heading><Text variant="secondary">Bordas, texto secundário e foco usam os overrides estruturais de alto contraste.</Text><Text variant="caption">Use Tab para inspecionar o anel de foco global.</Text></Stack></div><Text variant="small">O primeiro foco da página revela “Pular para o conteúdo”. Ícones exigem nome acessível. Links externos anunciam nova aba.<VisuallyHidden> Esta frase só é exposta a tecnologias assistivas.</VisuallyHidden></Text></Stack></Section>
    </Container>
  </div>;
}
